### PR TITLE
Save the complete DateTime when a scheduled product indexing finish.

### PR DESCRIPTION
**Pull request by oantonelli**

### CODE REVIEW

**Comment by oantonelli** [comment]
@shieldo Can you review this please.

**Comment by shieldo** [comment]
What is the purpose of the change? Is it so that it isn't necessary to call `setComplete` explicitly - you can just call `setStatus` when changing status and it does the right thing?  This would seem to make sense to me if that's the intention.

**Comment by oantonelli** [comment]
I was looking to know how long does it take a scheduled index to be complete. the `search_scheduled_index` table has the complete field but it is never updated.

**Comment by shieldo** [comment]
Sure.  Makes sense to me!  Thanks!

**Pull request merged**
