### PR TITLE
improve the composer deps & build (+ static analysis) + php 7.2

### PR DESCRIPTION
**Pull request by gsdevme**

### CODE REVIEW

**Comment by gsdevme** [comment]
@shieldo looks like Needle isn't actually compatible with Symfony v3

**Comment by shieldo** [comment]
@gsdevme This Travis build is actually installing a v4 of the Symfony dependency injection component, hence the failure (or at least one of them - the `SCOPE_PROTOTYPE` mention will need to replaced too).  I'll make a patch for future-compliance.

**Comment by shieldo** [comment]
@gsdevme We shouldn't _strictly_ be dropping Symfony 2.7 support until May, although it's probably unlikely anyone is using this library with 2.7. But if we are doing that, we can split out that change from this, and get rid of the `SCOPE_PROTOTYPE` BC logic as that was just for 2.7 support.

**Comment by shieldo** [comment]
Made a PR for the `DefinitionDecorator` part, though this will still likely fail phpstan as it won't check for `class_exists`/ `defined` checks etc.

**Comment by gsdevme** [comment]
Yeah it still continues to fail @shieldo  :(

**Comment by gsdevme** [comment]
I will add an exception in stan to this for now

**Comment by gsdevme** [comment]
```
 ------ ---------------------------------------------------------------------------------------------------------
  Line   DependencyInjection/MarkupNeedleExtension.php
 ------ ---------------------------------------------------------------------------------------------------------
  295    Access to undefined constant Symfony\Component\DependencyInjection\ContainerInterface::SCOPE_PROTOTYPE.
 ------ ---------------------------------------------------------------------------------------------------------
```

Ive also added an ignore here

**Pull request merged**
